{
 "title": "Analisador de Sentimento Dinamico",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cliente", "label": "Cliente", "query": "select c.nome  from clientes c" }
  ]
 },
 "panels": [
  {
   "title": "Sentimento nos ultimos 6 meses",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "   SELECT \r\n    s.tipo, \r\n    s.valor,\r\n    a.data_insercao \r\nFROM \r\n    clientes c\r\n    JOIN analisys a ON c.id = a.cliente_id\r\n    JOIN sentimentos s ON a.id = s.analisys_id\r\nWHERE \r\n    c.nome = $cliente \r\n    AND a.data_insercao >= date_trunc('month', current_date) - interval '6 months'\r\n    AND a.data_insercao < date_trunc('month', current_date) + interval '1 month';"
    }
   ]
  },
  {
   "title": "E-mail's dentro do mês",
   "type": "table",
   "gridPos": { "h": 22, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    to_char(a.data_insercao, 'YYYY-MM') AS mes_ano,\r\n    COUNT(*) AS quantidade\r\nFROM \r\n    clientes c\r\n    JOIN analisys a ON c.id = a.cliente_id\r\n    JOIN sentimentos s ON a.id = s.analisys_id\r\nWHERE \r\n    c.nome = $cliente \r\n    AND a.data_insercao >= date_trunc('month', current_date) - interval '6 months'\r\n    AND a.data_insercao < date_trunc('month', current_date) + interval '1 month'\r\nGROUP BY \r\n    to_char(a.data_insercao, 'YYYY-MM')\r\nORDER BY \r\n    to_char(a.data_insercao, 'YYYY-MM');\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT nome FROM clientes WHERE nome=$cliente "
    }
   ]
  },
  {
   "title": "Principais Sentimentos",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH sentiment_counts AS (\r\n    SELECT \r\n        c.nome, \r\n        s.tipo, \r\n        COUNT(*) AS count_tipo\r\n    FROM \r\n        clientes c\r\n        JOIN analisys a ON c.id = a.cliente_id\r\n        JOIN sentimentos s ON a.id = s.analisys_id\r\n    WHERE \r\n        c.nome = $cliente \r\n        AND a.data_insercao >= date_trunc('month', current_date) - interval '6 months'\r\n        AND a.data_insercao < date_trunc('month', current_date) + interval '1 month'\r\n    GROUP BY \r\n        c.nome, \r\n        s.tipo\r\n)\r\nSELECT     \r\n    tipo,\r\n    count_tipo\r\nFROM \r\n    sentiment_counts\r\nWHERE \r\n    count_tipo = (SELECT MAX(count_tipo) FROM sentiment_counts);\r\n"
    }
   ]
  }
 ]
}