avaliacoes_clientes = [
    "\"Boa noite a todos,\"",
    "\" \"",
    "\"Somente para alinhar no grupo, uma vez que já conversei com a @Santuxa via contato telefônico.  \",",
    "\" \"",
    "\"Por questões orçamentárias, não temos como aumentar o time de QAs com o Matheus Ciuffi. \",",
    "\" \"",
    "\"Permaneceremos com o Thiago Barbosa somente até retorno da Denise em férias.\",",
    "\" \"",
    "\"Abs,\",",
    "\" \"",
    "\"Tatiana Mazete \",",
    "\" \"",
    "\" \"",
    "\"Classificação: RESTRITA\",",
    "\"From: Luciano Fagundes de Oliveira <luciano.oliveira@yaman.com.br> \",",
    "\"Sent: quarta-feira, 21 de fevereiro de 2024 10:13\",",
    "\"To: Tatiana Mazete <tatiana_mazete@bancotoyota.com.br>\",",
    "\"Cc: Santuxa Ferreira Aragao <santuxa.aragao@yaman.com.br>; Marcelo Ribelato <marcelo.ribelato@yaman.com.br>; Adriana Barbosa <gft_app@bancotoyota.com.br>; Claudia Yamamoto <gft_cy@bancotoyota.com.br>; Aureliano Oliveira <aureliano_oliveira@bancotoyota.com.br>\",",
    "\"Subject: [EXTERNAL]: Decisão sobre alocação de recursos para cobertura de férias \",",
    "\" \"",
    "\"CUIDADO: Este e-mail foi originado de fora da organização. Não clique em links ou abra anexos a menos que reconheça o remetente e saiba que o conteúdo é seguro.\",",
    "\"Prezados,\",",
    "\" \"",
    "\"Espero que estejam bem. \",",
    "\" \"",
    "\"Gostaria de formalizar a decisão tomada durante nossa conversa via chat e posteriormente confirmada em uma chamada com Aureliano.\",",
    "\" \"",
    "\"Após considerarmos as demandas pendentes que ainda necessitam de homologação em Produtos e Marketing, bem como as responsabilidades atuais de nossa equipe, chegamos a uma decisão sobre a alocação de recursos para cobertura de férias.\",",
    "\" \"",
    "\"Decisão:\",",
    "\" \"",
    "\"•\tManteremos o Wellyson na sua squad atual (frente da Corretora) até o final do projeto.\",",
    "\"•\tTiago Barbosa permanecerá junto a Daniel até o dia 31/03/2024 , contribuindo não apenas com testes, mas também com apoio em outras atividades do projeto.\",",
    "\"•\tPara cobrir as tarefas adicionais durante as férias, propomos a inclusão de um QA adicional.\",",
    "\"o\tA sugestão aqui será o Matheus Ciuffi que irá realizar a seguinte cobertura:\",",
    "\"\tDenise Ferreira na squad Consórcio entre o dia 06/03 até o dia 20/03;\",",
    "\"\tIrani Fidelis na squad FastTrack entre o dia 01/04 até o dia 10/04;\",",
    "\"\tDiego Castor na squad Salesforce entre o dia 15/04 até o dia 23/04;\",",
    "\" \"",
    "\"Justificativa:\",",
    "\" \"",
    "\"•\tTiago Barbosa demonstrou uma participação significativa no projeto Parcelas Intermediárias, desempenhando várias funções essenciais, desde o entendimento de negócios até o preparo para acompanhamento do UAT, portanto a sua permanência é considerada benéfica para a continuidade e eficiência do projeto.\",",
    "\" \"",
    "\"A inclusão de um novo QA ajudará a manter o ritmo das atividades, garantindo que as responsabilidades de férias sejam atendidas sem sobrecarregar a equipe existente. \",",
    "\" \"",
    "\"Agradecemos a compreensão e colaboração de todos nesse processo. \",",
    "\"Estamos à disposição para discutir quaisquer dúvidas ou sugestões adicionais.\",",

]